# https://yunohost.org/en/packaging_manifest
packaging_format = 2

id = "django-bom"
name = "Django-Bom"
description.en = "Django-Bom is a Django-based Bill of Materials management system."
description.fr = "Django-Bom est un système de gestion de nomenclature basé sur Django."

version = "0.1.0~ynh4"

maintainers = ["Matteo Lucas"]

[upstream]
# Lien vers le projet d'origine
license = "GPL-3.0-or-later"
code = "https://github.com/mpkasp/django-bom"

[integration]
# YunoHost version requise
yunohost = ">=11.2"
helpers_version = "2.1" # https://yunohost.org/en/packaging_apps_helpers_v2.1
architectures = "all"
multi_instance = false  # Django-Bom est généralement installé en une seule instance
ldap = false  # Pas nécessaire sauf si on veu
