#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIRECTORY
#=================================================
ynh_script_progression "Backing up main application directory..."
ynh_backup "$install_dir"
ynh_backup "$data_dir"

# Sauvegarder l'environnement virtuel pour éviter de tout réinstaller
ynh_script_progression "Backing up Python virtual environment..."
ynh_backup "$install_dir/venv"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Backing up Nginx configuration..."
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE PostgreSQL DATABASE
#=================================================
ynh_script_progression "Backing up PostgreSQL database..."
pg_dump -U $postgresql_user -h localhost -d $postgresql_db > "$install_dir/db_backup.sql"
ynh_backup "$install_dir/db_backup.sql"

#=================================================
# BACKUP LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Backing up logrotate configuration..."
ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD CONFIGURATION
#=================================================
ynh_script_progression "Backing up systemd service configuration..."
ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================
ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
