#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP AND REMOVE SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping and removing systemd service '$app'..."

# Arrêter et désactiver Gunicorn
systemctl stop $app
systemctl disable $app
ynh_safe_rm "/etc/systemd/system/$app.service"

# Recharger systemd
systemctl daemon-reload

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================
if yunohost service status $app >/dev/null 2>&1; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove $app
fi

#=================================================
# REMOVE DATABASE (POSTGRESQL)
#=================================================
ynh_script_progression "Removing PostgreSQL database and user..."

# Supprimer
