#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#-------------------------------------------------
# LOAD SETTINGS FROM config_panel.toml

if [ -z "$debug_enabled" ]; then
	debug_enabled="0"
	ynh_app_setting_set --key=debug_enabled --value="$debug_enabled"
fi

if [ -z "$log_level" ]; then
	log_level="WARNING"
	ynh_app_setting_set --key=log_level --value="$log_level"
fi

if [ -z "$admin_email" ]; then
	admin_email="${admin}@${domain}"
    ynh_app_setting_set --key=admin_email --value="$admin_email"
fi

if [ -z "$default_from_email" ]; then
	default_from_email="${app}@${domain}"
	ynh_app_setting_set --key=default_from_email --value="$default_from_email"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."
ynh_systemctl --service=$app --action="stop" --log_path="$log_file"

#=================================================
# REMOVE OLD FILES AND CLEANUP
#=================================================
ynh_script_progression "Removing old virtual environment..."
rm -rf "$install_dir/venv"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Reconfiguring systemd service '$app'..."
ynh_config_add_systemd

#=================================================
# PYTHON VIRTUALENV & DEPENDENCIES UPDATE
#=================================================
ynh_script_progression "Creating new Python virtual environment..."
python3 -m venv "$install_dir/venv"

# Activer le virtualenv
source "$install_dir/venv/bin/activate"

# Mettre à jour pip et installer les dépendances
ynh_script_progression "Installing/updating dependencies..."
pip install --upgrade pip setuptools wheel
pip install --upgrade -r "$install_dir/requirements.txt"

#=================================================
# UPDATE DJANGO-BOM
#=================================================
ynh_script_progression "Updating Django-Bom and dependencies..."
pip install --upgrade git+https://github.com/mpkasp/django-bom.git

#=================================================
# MIGRATE DATABASE
#=================================================
ynh_script_progression "Applying database migrations..."
cd "$install_dir" || exit
source venv/bin/activate

python manage.py migrate --no-input
python manage.py collectstatic --no-input --clear

# Create/update Django superuser (set unusable password, because auth done via SSOwat):
python manage.py createsuperuser --username="$admin" --email="$(ynh_user_get_info --username="$admin" --key=mail)" || true

#=================================================
# RESTART SYSTEMD SERVICE
#=================================================
ynh_script_progression "Restarting systemd service '$app'..."
ynh_systemctl --service=$app --action="start" --log_path="$log_file"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading Nginx web server..."
ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed successfully!"
